image: Visual Studio 2019

before_build:
  - nuget restore TreeCalculator/TreeCalculator.sln
  - choco install opencover.portable
  - choco install codecov

build:
  project: TreeCalculator/TreeCalculator.sln

test_script:
  - dotnet test TreeCalculator/TreeCalculator.sln
  - OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"C:\projects\hw\TreeCalculator\TreeCalculator.Test\bin\Debug\netcoreapp3.1\TreeCalculator.Test.dll -noshadow" -filter:"+[TreeCalculator*]* -[TreeCalculator.Test*]*" -output:".\MyProject_coverage.xml"
  - codecov -f "MyProject_coverage.xml"
