image: Visual Studio 2019

before_build:
  - nuget restore Task21/Task21.sln
  - choco install opencover.portable
  - choco install codecov

build:
  project: Task21/Task21.sln

test_script:
  - dotnet test Task21/Task21.sln
  - OpenCover.Console.exe -register -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full C:\projects\hw\Task21\Task21.Tests\Task21.Test.csproj" -filter:"+[Task21*]* -[Task21.Test*]*" -output:".\my_app_coverage.xml"
  - codecov -f .\my_app_coverage.xml -t 5382e166-51cc-44e6-bf48-6a45c18b6ebd
