image: Visual Studio 2019

before_build:
  - nuget restore TreeCalculator/TreeCalculator.sln

build:
  project: TreeCalculator/TreeCalculator.sln

test_script:
  - dotnet test TreeCalculator/TreeCalculator.sln
