image: Visual Studio 2019

before_build:
  - nuget restore FunctionsOnLists/FunctionsOnLists.sln
  - choco install opencover.portable
  - choco install codecov

build:
  project: FunctionsOnLists/FunctionsOnLists.sln

test_script:
  - dotnet test FunctionsOnLists/FunctionsOnLists.sln
  - OpenCover.Console.exe -register -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full C:\projects\hw\FunctionsOnLists\FunctionsOnLists.Test\FunctionsOnLists.Test.csproj" -filter:"+[FunctionsOnLists*]* -[FunctionsOnLists.Test*]*" -output:".\my_app_coverage.xml"
  - codecov -f .\my_app_coverage.xml -t 5382e166-51cc-44e6-bf48-6a45c18b6ebd
