image: Visual Studio 2019

before_build:
  - nuget restore TreeCalculator/TreeCalculator.sln
  - choco install opencover.portable
  - choco install codecov

build:
  project: TreeCalculator/TreeCalculator.sln

test_script:
  - dotnet test TreeCalculator/TreeCalculator.sln
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full C:\projects\hw\TreeCalculator\TreeCalculator.Test\TreeCalculator.Test.csproj" -filter:"+[TreeCalculator*]* -[TreeCalculator.Test*]*" -output:".\my_app_coverage.xml"
  - codecov -f .\my_app_coverage.xml -t 5382e166-51cc-44e6-bf48-6a45c18b6ebd
