image: Visual Studio 2019

before_build:
  - nuget restore TreeCalculator/TreeCalculator.sln

build:
  project: TreeCalculator/TreeCalculator.sln

test_script:
  - dotnet test TreeCalculator/TreeCalculator.sln
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"TreeCalculator\TreeCalculator.Test\bin\Debug\netcoreapp3.1\TreeCalculator.Test.dll -noshadow" -output:"coverage.xml" -filter:"+[TreeCalculator*]* -[TreeCalculator.Test*]*"

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t 5382e166-51cc-44e6-bf48-6a45c18b6ebd
